export const MILLISECONDS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;
export const DAYS_PER_WEEK = 7;

export const FORTNIGHT_IN_WEEKS = 2;
export const DAYS_PER_FORTNIGHT = DAYS_PER_WEEK * FORTNIGHT_IN_WEEKS;
export const DAYS_PER_MONTH_APPROX = 30;
export const MONTHS_PER_QUARTER_APPROX = 3;
export const DAYS_PER_QUARTER_APPROX =
  DAYS_PER_MONTH_APPROX * MONTHS_PER_QUARTER_APPROX;
export const MONTHS_PER_HALF_YEAR = 6;
export const DAYS_PER_HALF_YEAR = DAYS_PER_MONTH_APPROX * MONTHS_PER_HALF_YEAR;
export const DAYS_PER_YEAR = 365;
export const YEARS_PER_LUSTRUM = 5;
export const DAYS_PER_FIVE_YEARS = YEARS_PER_LUSTRUM * DAYS_PER_YEAR;

export const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
export const SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;

export const MILLISECONDS_PER_MINUTE =
  MILLISECONDS_PER_SECOND * SECONDS_PER_MINUTE;
export const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * MINUTES_PER_HOUR;
export const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * HOURS_PER_DAY;
