import React from 'react';
import PropTypes from 'prop-types';
import './ErrorAlert.css';

/**
 * Unified error/warning/info alert component for consistent user feedback.
 *
 * Replaces inline error displays across the application with a consistent,
 * accessible pattern following WCAG AA standards. Supports multiple severity
 * levels (error/warning/info), optional dismiss functionality, and light/dark themes.
 *
 * Features:
 * - Three severity levels with appropriate colors, icons, and contrast ratios
 * - Accessible ARIA semantics (role="alert", aria-live, aria-atomic)
 * - Keyboard navigation (Tab to dismiss, Enter/Space to activate, Escape to dismiss)
 * - Responsive design (mobile, tablet, desktop)
 * - Light/dark mode support via CSS custom properties
 * - Optional dismiss button with clear accessibility labels
 * - Support for rich content via children prop
 *
 * @param {Object} props - Component props
 * @param {string | React.ReactNode} props.message - Error/warning/info message to display.
 *   Can be a string or JSX element for rich content.
 * @param {'error' | 'warning' | 'info'} [props.severity='error'] - Severity level
 *   controlling color, icon, and visual styling
 * @param {Function} [props.onDismiss] - Optional callback when dismiss button clicked.
 *   If provided, dismiss button appears. If not provided, no dismiss button shown.
 * @param {string | React.ReactNode} [props.icon] - Custom icon to override default.
 *   Can be an emoji string, JSX, or React icon component.
 * @param {string} [props.className] - Additional CSS class name for custom styling
 * @param {string} [props.id] - Unique ID for aria-describedby linking (auto-generated if not provided)
 * @param {string} [props.ariaLabel] - Custom aria-label for screen readers.
 *   If not provided, auto-generated from severity (e.g., "Error: ...")
 * @param {boolean} [props.showIcon=true] - Whether to show icon
 * @param {boolean} [props.showDismiss] - Whether to show dismiss button
 *   (default: true if onDismiss provided)
 * @param {React.ReactNode} [props.children] - Additional children rendered after message
 *   (useful for action links or details)
 * @returns {JSX.Element} Alert component
 *
 * @example
 * // Basic error with dismiss
 * <ErrorAlert
 *   message="Failed to parse CSV file"
 *   severity="error"
 *   onDismiss={() => setError(null)}
 * />
 *
 * @example
 * // Warning without dismiss
 * <ErrorAlert
 *   message="Large dataset detected. Analysis may take 1-2 minutes."
 *   severity="warning"
 *   showDismiss={false}
 * />
 *
 * @example
 * // Info with action button
 * <ErrorAlert
 *   message="Session loaded successfully"
 *   severity="info"
 *   onDismiss={() => setInfo(null)}
 * >
 *   <button onClick={handleViewDetails}>View Details</button>
 * </ErrorAlert>
 *
 * @see docs/work/implementation/error-alert-design.md - Full design specification
 */
export default function ErrorAlert({
  message,
  severity = 'error',
  onDismiss,
  icon,
  className = '',
  id,
  ariaLabel,
  showIcon = true,
  showDismiss,
  children,
}) {
  // Always call hooks at top level (React rules of hooks)
  const autoGeneratedId = React.useId();

  // Auto-generate ID if not provided
  const alertId = id || `error-alert-${autoGeneratedId}`;

  // Determine if dismiss button should be shown
  const shouldShowDismiss =
    showDismiss !== undefined ? showDismiss : !!onDismiss;

  // Default icons for each severity level
  const defaultIcons = {
    error: '⚠️',
    warning: '⚡',
    info: 'ℹ️',
  };

  const displayIcon = icon !== undefined ? icon : defaultIcons[severity];

  // Auto-generate aria-label from severity if not provided
  const severityLabels = {
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
  };
  const ariaLabelText =
    ariaLabel ||
    `${severityLabels[severity]}: ${typeof message === 'string' ? message : 'Alert message'}`;

  // Handle keyboard events (Escape to dismiss)
  const handleKeyDown = (e) => {
    if (e.key === 'Escape' && onDismiss && shouldShowDismiss) {
      e.preventDefault();
      onDismiss();
    }
  };

  return (
    <div
      role="alert"
      aria-live="assertive"
      aria-atomic="true"
      aria-label={ariaLabelText}
      id={alertId}
      className={`error-alert error-alert--${severity} ${className}`.trim()}
      onKeyDown={handleKeyDown}
      tabIndex={shouldShowDismiss && onDismiss ? 0 : -1}
    >
      {showIcon && displayIcon && (
        <span className="error-alert__icon" aria-hidden="true">
          {displayIcon}
        </span>
      )}
      <div className="error-alert__message">{message}</div>
      {children && <div className="error-alert__actions">{children}</div>}
      {shouldShowDismiss && onDismiss && (
        <button
          type="button"
          onClick={onDismiss}
          aria-label={`Dismiss ${severity} message`}
          className="error-alert__dismiss"
        >
          ×
        </button>
      )}
    </div>
  );
}

ErrorAlert.propTypes = {
  message: PropTypes.oneOfType([PropTypes.string, PropTypes.node]).isRequired,
  severity: PropTypes.oneOf(['error', 'warning', 'info']),
  onDismiss: PropTypes.func,
  icon: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  className: PropTypes.string,
  id: PropTypes.string,
  ariaLabel: PropTypes.string,
  showIcon: PropTypes.bool,
  showDismiss: PropTypes.bool,
  children: PropTypes.node,
};
